package com.example.jianglei.greendaotestdemo.db.dao;

import android.database.sqlite.SQLiteDatabase;

import com.example.jianglei.greendaotestdemo.db.bean.User;
import com.example.jianglei.greendaotestdemo.db.bean.WangShan;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig wangShanDaoConfig;

    private final UserDao userDao;
    private final WangShanDao wangShanDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        wangShanDaoConfig = daoConfigMap.get(WangShanDao.class).clone();
        wangShanDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        wangShanDao = new WangShanDao(wangShanDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(WangShan.class, wangShanDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        wangShanDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public WangShanDao getWangShanDao() {
        return wangShanDao;
    }

}
